[package]
name = "controller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gilrs = "0.10.4"
robust-arduino-serial = "0.1.1"
serial = "0.4.0"
serial2 = "0.2.16"
